name: Cross Browser Testing - Selenium - CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  chrome:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
     
    - name: Build with Maven
      run: mvn -B clean test
      
  firefox:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version
     
    - name: Build with Maven
      run: mvn -B clean test
      
  edge:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - uses: browser-actions/setup-edge@v1
    - run: edge --version
     
    - name: Build with Maven
      run: mvn -B clean test
      
